### ISSUE TITLE
Broken Link on https://oscar.grycap.net/blog/post-oscar-node-red/

### ISSUE THREAD

**Issue by esparig** [grycap/oscar-landing#42]
In [Line 303](https://github.com/grycap/oscar-landing/blob/13696a68e571e1dfcd3854d643e7ef07325132be/content/english/blog/post-oscar-node-red.md?plain=1#L303) the link to sample workflow is broken.

**Comment by gmolto** [comment]
Thanks! Please @vicente87 double check and fix.

**Comment by vicente87** [comment]
We made changes to the repository names and it was not updated on the blog
